### ISSUE TITLE
Java outOfMemory error on ExportToFileJob

### ISSUE THREAD

**Issue by ltnd** [marklogic-community/marklogic-data-movement-components#18]
On the code :
```
ExportToFileJob exportToFileJob = new ExportToFileJob();
exportToFileJob.setFileHeader(header);
exportToFileJob.setExportFile(new File(getFileName()));
exportToFileJob.setWhereUrisQuery(query);
exportToFileJob.setJobName(jobName);
exportToFileJob.setBatchSize(batchSize);
exportToFileJob.setThreadCount(threadCount);
exportToFileJob.setIncludeXmlOutputListener(false);
ServerTransform serverTransform = new ServerTransform("extractCSV");
exportToFileJob.getExportListener().withTransform(serverTransform);
QueryBatcherJobTicket batcherJobTicket = exportToFileJob.run(finalDB);
```
We have the following error on collecting large URI as it is loaded in memory and it not scales for large DB :
[ERROR] org.springframework.batch.core.step.AbstractStep - Encountered an error executing step extractGRBlockStep in job extractGRBlockJob
java.lang.OutOfMemoryError: Java heap space
                at java.util.Arrays.copyOf(Arrays.java:3181)
                at java.util.ArrayList.grow(ArrayList.java:265)
                at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
                at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
                at java.util.ArrayList.add(ArrayList.java:462)
                at com.marklogic.client.impl.OkHttpServices.getPartList(OkHttpServices.java:5341)
                at com.marklogic.client.impl.OkHttpServices.makeResults(OkHttpServices.java:4346)
                at com.marklogic.client.impl.OkHttpServices.postIteratedResourceImpl(OkHttpServices.java:3834)
                at com.marklogic.client.impl.OkHttpServices.postEvalInvoke(OkHttpServices.java:3768)
                at com.marklogic.client.impl.ServerEvaluationCallImpl.eval(ServerEvaluationCallImpl.java:164)
                at com.marklogic.client.ext.datamovement.UrisQueryQueryBatcherBuilder.buildQueryBatcher(UrisQueryQueryBatcherBuilder.java:79)
                at com.marklogic.client.ext.datamovement.job.AbstractQueryBatcherJob.run(AbstractQueryBatcherJob.java:59)

**Comment by rjrudin** [comment]
Can you use something besides whereUrisQuery? The UrisQueryQueryBatcherBuilder is a convenience for selecting documents via cts.uris, but doing so requires the use of /v1/eval. 

The better approach would be to use a different QueryBatcherBuilder or construct your own, possibly one that uses the DatabaseClient to construct a QueryManager and then builds something like a RawStructuredQueryDefinition.

**Comment by rjrudin** [comment]
Closing due to no response, recommend using the approach I mentioned above.
